// Package job normalizes scheduler-specific in-job environment variables (PBS / SLURM)
// into a common MU_* set, so a job script reads MU_* and runs unchanged under either
// scheduler. Most of the map is trivial aliasing; the one that needs logic is NODEFILE:
// PBS gives a file of hostnames, SLURM a compressed nodelist string — so on SLURM mu
// expands it via `scontrol show hostnames` into a file, matching PBS's shape.
package job

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

type scheduler int

const (
	none scheduler = iota
	pbs
	slurm
)

// detect reads which scheduler set the job env; the presence of its jobid var is the tell.
func detect() scheduler {
	switch {
	case os.Getenv("SLURM_JOB_ID") != "":
		return slurm
	case os.Getenv("PBS_JOBID") != "":
		return pbs
	default:
		return none
	}
}

func (s scheduler) String() string {
	if s == slurm {
		return "slurm"
	}
	return "pbs"
}

// varMap is MU_* → (PBS var, SLURM var). An empty source means that scheduler has no
// equivalent (the row is skipped for it), so a PBS job never gets an empty SLURM-only var.
var varMap = []struct{ mu, pbsVar, slurmVar string }{
	{"MU_JOBID", "PBS_JOBID", "SLURM_JOB_ID"},
	{"MU_JOBNAME", "PBS_JOBNAME", "SLURM_JOB_NAME"},
	{"MU_SUBMIT_DIR", "PBS_O_WORKDIR", "SLURM_SUBMIT_DIR"},
	{"MU_SUBMIT_HOST", "PBS_O_HOST", "SLURM_SUBMIT_HOST"},
	{"MU_QUEUE", "PBS_QUEUE", "SLURM_JOB_PARTITION"},
	{"MU_ACCOUNT", "PBS_ACCOUNT", "SLURM_JOB_ACCOUNT"},
	{"MU_NUM_NODES", "PBS_NUM_NODES", "SLURM_JOB_NUM_NODES"},
	{"MU_PPN", "PBS_NUM_PPN", "SLURM_NTASKS_PER_NODE"},
	{"MU_NTASKS", "", "SLURM_NTASKS"},
	{"MU_ARRAY_INDEX", "PBS_ARRAY_INDEX", "SLURM_ARRAY_TASK_ID"},
	{"MU_ARRAY_JOBID", "", "SLURM_ARRAY_JOB_ID"},
}

// Env returns a POSIX-sh snippet (`export MU_*=…`) normalizing the active scheduler's job
// variables, for `eval "$(mu job env)"` at the top of a job script. Errors when not inside
// a job (no scheduler jobid var) so an accidental `eval` in a login shell is a clear no-op.
func Env() (string, error) {
	sched := detect()
	if sched == none {
		return "", fmt.Errorf("not inside a PBS or SLURM job (no PBS_JOBID / SLURM_JOB_ID)")
	}
	var b strings.Builder
	b.WriteString("# mayhl_utils job env — normalized MU_* (generated by `mu job env`)\n")
	fmt.Fprintf(&b, "export MU_SCHEDULER=%s\n", sched)
	for _, v := range varMap {
		src := v.pbsVar
		if sched == slurm {
			src = v.slurmVar
		}
		if src == "" {
			continue
		}
		if val := os.Getenv(src); val != "" {
			fmt.Fprintf(&b, "export %s=%s\n", v.mu, shQuote(val))
		}
	}
	// TMPDIR is standard on both; pass it through under the MU_ name for symmetry.
	if t := os.Getenv("TMPDIR"); t != "" {
		fmt.Fprintf(&b, "export MU_TMPDIR=%s\n", shQuote(t))
	}
	// NODEFILE — the one mapping that isn't a rename.
	nf, err := nodeFile(sched)
	if err != nil {
		return "", err
	}
	if nf != "" {
		fmt.Fprintf(&b, "export MU_NODEFILE=%s\n", shQuote(nf))
	}
	return b.String(), nil
}

// nodeFile returns a path to a hostname-per-line file for the job. PBS already provides one
// ($PBS_NODEFILE); SLURM gives a compressed nodelist ("node[01-04]"), expanded here via
// `scontrol show hostnames` into a stable per-job file so downstream tools (mpirun -hostfile,
// etc.) see the same shape under either scheduler.
func nodeFile(sched scheduler) (string, error) {
	if sched == pbs {
		return os.Getenv("PBS_NODEFILE"), nil // already a file path
	}
	list := os.Getenv("SLURM_JOB_NODELIST")
	if list == "" {
		return "", nil
	}
	out, err := exec.Command("scontrol", "show", "hostnames", list).Output()
	if err != nil {
		return "", fmt.Errorf("expand SLURM nodelist %q via scontrol: %w", list, err)
	}
	dir := os.Getenv("TMPDIR")
	if dir == "" {
		dir = "/tmp"
	}
	path := filepath.Join(dir, "mu-nodefile-"+os.Getenv("SLURM_JOB_ID"))
	if err := os.WriteFile(path, out, 0o644); err != nil {
		return "", fmt.Errorf("write %s: %w", path, err)
	}
	return path, nil
}

// shQuote single-quotes a value for safe `eval` — job vars can hold spaces or shell
// metacharacters (a job name, a submit dir with a space).
func shQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}
