package job

import (
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
	"time"
)

// Prep gives each job its own throwaway copy of the case dir to run in: sibling
// <submitdir>_<jobid>, inputs copied in (scheduler log files excluded), run.toml
// provenance dropped, and a shell snippet returned for the job-script preamble
//
//	eval "$(mu job env)"
//	eval "$(mu job prep)"
//
// The snippet owns the failure semantics: a failed prep must kill the job, never
// let it compute in the submit dir (that's the authored $HOME/case tree).

// jobContext resolves the ids prep needs, preferring the MU_* set (job env already
// eval'd) with the raw scheduler vars as fallback — so prep works either way. The
// short id is the jobid's leading digit run (PBS "12345.server" → "12345"), plus a
// "-<index>" for array subjobs so parallel indices can't share a run dir.
func jobContext() (shortID, submitDir string, err error) {
	raw := firstEnv("MU_JOBID", "SLURM_JOB_ID", "PBS_JOBID")
	submitDir = firstEnv("MU_SUBMIT_DIR", "SLURM_SUBMIT_DIR", "PBS_O_WORKDIR")
	if raw == "" || submitDir == "" {
		return "", "", fmt.Errorf("not inside a job (no jobid/submit-dir vars — run after `eval \"$(mu job env)\"`)")
	}
	i := 0
	for i < len(raw) && raw[i] >= '0' && raw[i] <= '9' {
		i++
	}
	if i == 0 {
		return "", "", fmt.Errorf("jobid %q has no leading numeric id", raw)
	}
	shortID = raw[:i]
	if idx := firstEnv("MU_ARRAY_INDEX", "SLURM_ARRAY_TASK_ID", "PBS_ARRAY_INDEX"); idx != "" {
		shortID += "-" + idx
	}
	return shortID, submitDir, nil
}

func firstEnv(names ...string) string {
	for _, n := range names {
		if v := os.Getenv(n); v != "" {
			return v
		}
	}
	return ""
}

// RunDir resolves the current job's run dir without side effects (`prep --path`).
func RunDir() (string, error) {
	id, submitDir, err := jobContext()
	if err != nil {
		return "", err
	}
	return submitDir + "_" + id, nil
}

// Prep creates and fills the run dir, then returns the eval snippet. An existing
// run dir means a requeue: reuse it WITHOUT re-copying — it may hold partial
// outputs, and re-copying would clobber run state with pristine inputs (run.toml
// is only written if missing, preserving the original record).
func Prep() (snippet string, reused bool, err error) {
	id, submitDir, err := jobContext()
	if err != nil {
		return "", false, err
	}
	runDir := submitDir + "_" + id
	if _, serr := os.Lstat(runDir); serr == nil {
		reused = true
	} else {
		if err := copyTree(submitDir, runDir); err != nil {
			return "", false, fmt.Errorf("copy %s → %s: %w", submitDir, runDir, err)
		}
	}
	if _, serr := os.Stat(filepath.Join(runDir, "run.toml")); os.IsNotExist(serr) {
		if err := os.WriteFile(filepath.Join(runDir, "run.toml"), []byte(runTOML(id, submitDir)), 0o644); err != nil {
			return "", false, fmt.Errorf("write run.toml: %w", err)
		}
	}

	var b strings.Builder
	fmt.Fprintf(&b, "# mayhl_utils job prep — run dir for job %s (generated by `mu job prep`)\n", id)
	fmt.Fprintf(&b, "export MU_RUN_DIR=%s\n", shQuote(runDir))
	b.WriteString("cd \"$MU_RUN_DIR\" || exit 1\n")
	return b.String(), reused, nil
}

// schedulerLog matches the scheduler's stdout/stderr drop files for ANY jobid —
// old runs' logs accumulate in the case dir and must not be snapshotted into new
// runs: PBS `<name>.o12345`/`.e12345`, SLURM `slurm-12345.out` (array `_7` form too).
var schedulerLog = regexp.MustCompile(`(\.[oe][0-9]+|^slurm-[0-9]+(_[0-9]+)?\.out)$`)

// copyTree copies src into dst (fresh), preserving file modes and symlinks,
// skipping scheduler log files. Everything else copies — the run dir is the
// as-run snapshot, and faithfully recording a stray file is a feature.
func copyTree(src, dst string) error {
	return filepath.WalkDir(src, func(p string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		rel, err := filepath.Rel(src, p)
		if err != nil {
			return err
		}
		target := filepath.Join(dst, rel)
		info, err := d.Info()
		if err != nil {
			return err
		}
		switch {
		case d.IsDir():
			return os.MkdirAll(target, info.Mode().Perm())
		case info.Mode()&os.ModeSymlink != 0:
			link, err := os.Readlink(p)
			if err != nil {
				return err
			}
			return os.Symlink(link, target)
		case schedulerLog.MatchString(d.Name()):
			return nil
		default:
			return copyFile(p, target, info.Mode().Perm())
		}
	})
}

func copyFile(src, dst string, perm os.FileMode) error {
	in, err := os.Open(src)
	if err != nil {
		return err
	}
	defer func() { _ = in.Close() }()
	out, err := os.OpenFile(dst, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, perm)
	if err != nil {
		return err
	}
	if _, err := io.Copy(out, in); err != nil {
		_ = out.Close()
		return err
	}
	return out.Close()
}

// runTOML renders the provenance record: the rows the future sim-manager DB
// derives from, written where they can't desync — inside the run itself. The
// inputs' commit is the one fact unreconstructible later; dirty is case-scoped
// (uncommitted edits under the submit dir), so mid-edit sibling cases don't
// taint this run's record. No git → the git fields are simply absent.
func runTOML(id, submitDir string) string {
	var b strings.Builder
	b.WriteString("# run provenance — written by `mu job prep` at job start\n")
	fmt.Fprintf(&b, "jobid = %q\n", firstEnv("MU_JOBID", "SLURM_JOB_ID", "PBS_JOBID"))
	if s := os.Getenv("MU_SCHEDULER"); s != "" { // job env's verdict wins over re-detection
		fmt.Fprintf(&b, "scheduler = %q\n", s)
	} else if d := detect(); d != none {
		fmt.Fprintf(&b, "scheduler = %q\n", d.String())
	}
	fmt.Fprintf(&b, "started = %q\n", time.Now().Format(time.RFC3339))
	if c := os.Getenv("BC_HOST"); c != "" {
		fmt.Fprintf(&b, "cluster = %q\n", c)
	}
	if q := firstEnv("MU_QUEUE", "SLURM_JOB_PARTITION", "PBS_QUEUE"); q != "" {
		fmt.Fprintf(&b, "queue = %q\n", q)
	}
	if rel, ok := gitOut(submitDir, "rev-parse", "--show-prefix"); ok {
		fmt.Fprintf(&b, "case = %q\n", strings.TrimSuffix(rel, "/"))
	}
	if commit, ok := gitOut(submitDir, "rev-parse", "HEAD"); ok {
		fmt.Fprintf(&b, "commit = %q\n", commit)
		status, _ := gitOut(submitDir, "status", "--porcelain", "--", ".")
		fmt.Fprintf(&b, "dirty = %v\n", status != "")
	}
	return b.String()
}

// gitOut runs git in dir and returns trimmed stdout; ok=false outside a repo or
// without git — provenance degrades to fewer fields, never to an error.
func gitOut(dir string, args ...string) (string, bool) {
	out, err := exec.Command("git", append([]string{"-C", dir}, args...)...).Output()
	if err != nil {
		return "", false
	}
	return strings.TrimSpace(string(out)), true
}
