// Package shellinit generates the shell integration that `mu setup shell-init`
// prints for `eval "$(mu setup shell-init)"` at shell startup. It emits a per-node
// dispatcher plus one thin wrapper per configured node, all driven by the same
// config.toml the engine reads — so adding a node in the config makes its command
// appear, with no hand-maintained alias codegen.
package shellinit

import (
	"fmt"
	"os"
	"strings"
	"time"

	shellassets "github.com/mayhl/mayhl_utils"
	"github.com/mayhl/mayhl_utils/internal/config"
	"github.com/mayhl/mayhl_utils/internal/doctor"
)

// The dispatcher: bare `<node>` connects (interactive ssh), `<node> push|pull`
// transfer via the engine, and `<node> <anycmd>` runs that command over ssh. A
// leading pure-integer arg pins a numbered login node — `<node> N` rewrites the
// target's node segment to `<node>NN` (zero-padded, per the 01,02,… convention),
// then the rest of the grammar composes (bare → connect, else → remote-exec).
// push/pull stay node-level (mu cp resolves its own target). It leans on the shell
// framework's seam helpers (mu_auth, mu_ssh_login, $MU_SSH).
//
// The numeric guard uses a portable `case *[!0-9]*` test (no extglob) so it works
// in both bash and zsh. `<node> -h|--help` prints the grammar.
//
// Remote-exec runs `bash -lc` (login shell) so HPC modules/scheduler load from
// /etc/profile.d — which `zsh -l` does NOT source. That login profile spews a
// benign dbus/X11 error over non-interactive ssh; it's filtered from stderr via
// MU_SSH_STDERR_FILTER (default drops that message; process substitution keeps the
// command's exit code and lets real errors through). TEMPORARY workaround for the
// cluster's /etc/profile.d — see the dbus-filter note.
const helper = `_mu_node_help() {
  local n=$1
  printf '%s\n' \
    "$n - HPC shorthand for the '$n' cluster" \
    "  $n                connect (interactive ssh, default login)" \
    "  $n N              connect to login node N ($n 3 -> ${n}03)" \
    "  $n <cmd>          run <cmd> on $n over ssh" \
    "  $n N <cmd>        run <cmd> on login node N" \
    "  $n push SRC DST   upload   (mu cp push)" \
    "  $n pull SRC DST   download (mu cp pull)" \
    "  $n mstat [-a]     show $n's queue (mu hpc queue --node $n)" \
    "  $n -h | --help    show this help"
}
_mu_node() {
  local node=$1 target=$2; shift 2
  case ${1:-} in
    -h|--help) _mu_node_help "$node" ;;
    push) shift; mu cp push "$node" "$@" ;;
    pull) shift; mu cp pull "$node" "$@" ;;
    mstat) shift; mu hpc queue --node "$node" "$@" ;;
    "")   mu_auth && mu_ssh_login "$target" ;;
    *)
      case $1 in
        ''|*[!0-9]*) : ;;
        *) target="${target%%.*}$(printf '%02d' "$1").${target#*.}"; shift ;;
      esac
      if [ "$#" -eq 0 ]; then
        mu_auth && mu_ssh_login "$target"
      else
        mu_auth && ${MU_SSH:-ssh} -q "$target" "bash -lc \"$*\"" 2> >(grep -vE "${MU_SSH_STDERR_FILTER:-dbus-update-activation-environment|^Cannot continue}" >&2)
      fi
      ;;
  esac
}
`

// Generate returns the shell code to eval at startup: the config as exports (so
// legacy shell consumers — status.sh, mu_kitty_bootstrap — work with config.env
// gone), then the per-node dispatchers. The current system ($MU_NODE, else
// $BC_HOST) is skipped — no self ssh/cp dispatcher.
func Generate() string {
	targets := config.NodeTargets()
	self := selfNode()

	var nodes []string
	for _, n := range config.NodeNames() {
		if n != self {
			nodes = append(nodes, n)
		}
	}

	var b strings.Builder
	b.WriteString("# mayhl_utils shell integration — generated by `mu setup shell-init` (do not edit)\n")
	b.WriteString(configExports())
	b.WriteString(miseEnv())
	b.WriteString(platformSeam())
	b.WriteString(sharedTooling())
	b.WriteString(doctorCheckup())
	b.WriteString(helper)
	// Clear any stale same-named aliases (e.g. a leftover bare-node ssh alias from
	// the old connect.sh codegen), then define the dispatchers inside a NESTED
	// eval. zsh parses a whole eval block up-front and refuses a function def over
	// a live alias — the nested eval defers parsing the defs until after the
	// unalias has executed. (No dispatcher body contains a single quote.)
	if len(nodes) > 0 {
		fmt.Fprintf(&b, "unalias %s 2>/dev/null || :\n", strings.Join(nodes, " "))
		b.WriteString("eval '\n")
		for _, n := range nodes {
			fmt.Fprintf(&b, "%s() { _mu_node %s \"%s\" \"$@\"; }\n", n, n, targets[n])
		}
		b.WriteString("'\n")
	}
	b.WriteString(frontDoors())
	return b.String()
}

// frontDoors emits the short shell front-doors for the process, log, and queue planes:
// mps/mkill/mlog (process + event log — always) and the queue pair under the configured idiom
// (config.toml [shell] queue_aliases) — mstat/mdel (pbs, default), mqueue/mcancel
// (slurm), or both. Bare `mstat` runs the CURRENT cluster's scheduler locally (mu hpc
// queue, no --node); `<node> mstat` routes through the per-node dispatcher above. The
// queue pair is emitted only when a cluster is configured; mps/mkill always. Each uses
// the unalias + nested-eval dance the dispatchers use — zsh won't define a function
// over a live alias, and the nested eval defers parsing the def until the unalias runs
// (no body contains a single quote).
func frontDoors() string {
	type door struct{ name, body string }
	doors := []door{
		{"mps", `mu ps "$@"`},
		{"mkill", `mu ps kill "$@"`},
		{"mlog", `mu log "$@"`},
	}
	if len(config.NodeNames()) > 0 {
		stat := door{"mstat", `mu hpc queue "$@"`}
		del := door{"mdel", `mu hpc queue kill "$@"`}
		queue := door{"mqueue", `mu hpc queue "$@"`}
		cancel := door{"mcancel", `mu hpc queue kill "$@"`}
		switch config.QueueAliases() {
		case "slurm":
			doors = append(doors, queue, cancel)
		case "both":
			doors = append(doors, stat, del, queue, cancel)
		default: // "pbs"
			doors = append(doors, stat, del)
		}
		// Scheduler-neutral read/state verbs — same name whatever the idiom (no clean
		// squeue word for "info"/"peek"/"hold"/"history").
		doors = append(
			doors,
			door{"minfo", `mu hpc queue info "$@"`},
			door{"mpeek", `mu hpc queue peek "$@"`},
			door{"mhold", `mu hpc queue hold "$@"`},
			door{"mrls", `mu hpc queue release "$@"`},
			door{"mhist", `mu hpc queue hist "$@"`},
		)
	}

	names := make([]string, len(doors))
	for i, d := range doors {
		names[i] = d.name
	}
	var b strings.Builder
	fmt.Fprintf(&b, "unalias %s 2>/dev/null || :\n", strings.Join(names, " "))
	b.WriteString("eval '\n")
	for _, d := range doors {
		fmt.Fprintf(&b, "%s() { %s; }\n", d.name, d.body)
	}
	b.WriteString("'\n")
	return b.String()
}

// configExports mirrors config.toml back into the MU_* environment for the legacy
// shell code that still reads it (mu_auth, mu_status). The Go engine reads
// config.toml directly; this is the bridge that replaced config.env. MU_SSH stays
// a platform seam. TODO: retire this bridge once those shell consumers call `mu`.
func configExports() string {
	var b strings.Builder
	// Mode (local/hpc), derived from MU_SYSTEM/$BC_HOST. init.sh used to export this; the
	// binary owns it now so consumers (the .config web-search gate, mise MISE_ENV) still see
	// it once init.sh is retired. Unguarded — always set, cheap.
	sys := "local"
	if onHPC() {
		sys = "hpc"
	}
	fmt.Fprintf(&b, "export MU_SYSTEM=%q\n", sys)
	if u := config.HPCUser(); u != "" {
		fmt.Fprintf(&b, "export MU_HPC_UNAME=%q\n", u)
	}
	defs := config.ClusterDefs()
	names := make([]string, 0, len(defs))
	for _, c := range defs {
		names = append(names, c.Name)
		cu := strings.ToUpper(c.Name)
		fmt.Fprintf(&b, "export MU_CLUSTER_%s_DOMAIN=%q\n", cu, c.Domain)
		fmt.Fprintf(&b, "export MU_CLUSTER_%s_NODES=%q\n", cu, strings.Join(c.Nodes, " "))
	}
	fmt.Fprintf(&b, "export MU_CLUSTERS=%q\n", strings.Join(names, " "))
	fmt.Fprintf(&b, "export MU_HPC_RSYNC_OPTS=%q\n", config.RsyncOpts())
	fmt.Fprintf(&b, "export MU_SSH_TRANSFER_OPTS=%q\n", config.SSHTransferOpts())
	fmt.Fprintf(&b, "export MU_SSHFS_ROOT=%q\n", config.SSHFSRoot())
	// ossh binary path (machine-specific) → the platform seam reads it (MU_OSSH) to
	// override MU_SSH. Only emitted when configured; unset → the seam uses plain ssh.
	if p := config.OSSHPath(); p != "" {
		fmt.Fprintf(&b, "export MU_OSSH=%q\n", p)
	}
	return b.String()
}

// miseEnv composes MISE_ENV ahead of any mise activation, in portable sh so bash and
// zsh onboard targets get the same tiers (this lived zsh-only in .config's
// zsh.tools.zsh, which now keeps just the activation). Runtime conditionals, not
// generation-time: MU_TOOLCHAIN comes from a `module load mu-toolchain` and varies per
// shell. Comma-composes so a pre-set MISE_ENV survives. Emitted right after
// configExports so its MU_SYSTEM export is already in force.
//
//	hpc — the nvim toolchain stack (config.hpc.toml), HPC boxes only; SKIPPED when the
//	shared mu-toolchain module provides it (its modulefile setenvs MU_TOOLCHAIN), so a
//	per-user fmt opt-in never re-installs module-owned base+hpc.
//	fmt — opt-in formatter/lint/DAP enforcement via MU_MODULES containing fmt.
func miseEnv() string {
	return `if [ -z "${MU_TOOLCHAIN:-}" ] && { [ -n "${BC_HOST:-}" ] || [ "${MU_SYSTEM:-}" = "hpc" ]; }; then
  export MISE_ENV="${MISE_ENV:+$MISE_ENV,}hpc"
fi
case ",${MU_MODULES:-}," in *,fmt,*) export MISE_ENV="${MISE_ENV:+$MISE_ENV,}fmt" ;; esac
`
}

// platformSeam emits the shell support libs (compat/log) and the connectivity seam
// (MU_SSH / mu_ssh_login / mu_auth) so the binary is self-sufficient: a box needs no
// mayhl_utils checkout for the node dispatchers (which call these helpers) to work. The
// blocks are the embedded lib/*.sh + platform/*.sh verbatim, each guarded so a dev box
// whose init.sh already sourced them is a no-op — and since the emitted text IS the
// embedded source, any redefinition is byte-identical. hpc vs local seam is picked by the
// detected mode; configExports() (which sets MU_OSSH) is emitted before this.
func platformSeam() string {
	seam := shellassets.PlatformLocalSH
	if onHPC() {
		seam = shellassets.PlatformHPCSH
	}
	var b strings.Builder
	// support libs (mu_log/mu_have/mu_indirect/…) — the seam + dispatchers depend on them.
	b.WriteString("command -v mu_log >/dev/null 2>&1 || {\n")
	b.WriteString(shellassets.CompatSH)
	b.WriteString(shellassets.LogSH)
	b.WriteString("}\n")
	// connectivity seam (MU_SSH + mu_ssh_login + mu_auth).
	b.WriteString("command -v mu_ssh_login >/dev/null 2>&1 || {\n")
	b.WriteString(seam)
	b.WriteString("}\n")
	return b.String()
}

// sharedTooling emits the portable shared helpers (tar shims qtar/gtar/bqtar/bgtar,
// status mu_status/mu_ctx, and gkill/qffmpeg/mytb/mu_run) so they exist on a binary-only
// box too. Guarded on mu_run (unique to utils.sh) so a dev box whose init.sh already
// sourced shared/*.sh is a no-op — the emitted text is the embedded source, so any
// redefinition is byte-identical. Depends on compat/log (platformSeam) + MU_* exports
// (configExports), both emitted above. Cosmetic aliases (vim/EDITOR) stay in .config.
func sharedTooling() string {
	var b strings.Builder
	b.WriteString("command -v mu_run >/dev/null 2>&1 || {\n")
	b.WriteString(shellassets.TarSH)
	b.WriteString(shellassets.StatusSH)
	b.WriteString(shellassets.UtilsSH)
	b.WriteString("}\n")
	return b.String()
}

// doctorCheckup emits the throttled health check: at most one background `mu doctor
// --checkup` per doctor.CheckupEvery, launched disowned so startup never waits on it.
// The fast path is builtin-only reads (`date +%s` is the one exec). A WARN/FAIL run
// leaves doctor.notice, printed at the NEXT shell start — async output landing over a
// live prompt is worse than a one-shell delay; a healthy run clears it. mu re-checks
// the stamp, so racing shells collapse to one run. Paths mirror doctor's Stamp/Notice.
func doctorCheckup() string {
	return fmt.Sprintf(`_mu_dc="${XDG_CACHE_HOME:-$HOME/.cache}/mayhl_utils"
[ -r "$_mu_dc/doctor.notice" ] && cat "$_mu_dc/doctor.notice" || :
_mu_dt=0
[ -r "$_mu_dc/doctor.stamp" ] && read -r _mu_dt < "$_mu_dc/doctor.stamp" || :
case $_mu_dt in ''|*[!0-9]*) _mu_dt=0 ;; esac
if [ $(( $(date +%%s) - _mu_dt )) -ge %d ]; then
  (mu doctor --checkup >/dev/null 2>&1 &)
fi
unset _mu_dc _mu_dt
`, int(doctor.CheckupEvery/time.Second))
}

// onHPC reports whether shell-init should emit the HPC seam: an explicit MU_SYSTEM wins,
// else $BC_HOST (set on HPC login/compute nodes) marks HPC. Mirrors init.sh's derivation.
func onHPC() bool {
	if s := os.Getenv("MU_SYSTEM"); s != "" {
		return s == "hpc"
	}
	return os.Getenv("BC_HOST") != ""
}

// selfNode is the node this shell is running on, if any (compute/login nodes set
// $BC_HOST reliably; $MU_NODE is an explicit override).
func selfNode() string {
	if n := os.Getenv("MU_NODE"); n != "" {
		return n
	}
	return os.Getenv("BC_HOST")
}
