// Package shellinit generates the shell integration that `mu shell-init` prints
// for `eval "$(mu shell-init)"` at shell startup. It emits a shared per-node
// dispatcher plus one thin wrapper per configured node, all driven by the same
// config.toml the engine reads — so adding a node in the config makes its command
// appear, with no hand-maintained alias codegen.
package shellinit

import (
	"fmt"
	"os"
	"strings"

	"github.com/mayhl/mayhl_utils/internal/config"
)

// The dispatcher: bare `<node>` connects (interactive ssh), `<node> push|pull`
// transfer via the engine, and `<node> <anycmd>` runs that command over ssh. It
// leans on the shell framework's seam helpers (mu_auth, mu_ssh_login, $MU_SSH).
//
// Remote-exec runs `bash -lc` (login shell) so HPC modules/scheduler load from
// /etc/profile.d — which `zsh -l` does NOT source. That login profile spews a
// benign dbus/X11 error over non-interactive ssh; it's filtered from stderr via
// MU_SSH_STDERR_FILTER (default drops that message; process substitution keeps the
// command's exit code and lets real errors through). TEMPORARY workaround for the
// cluster's /etc/profile.d — see the dbus-filter note.
const helper = `_mu_node() {
  local node=$1 target=$2; shift 2
  case ${1:-} in
    push) shift; mu cp push "$node" "$@" ;;
    pull) shift; mu cp pull "$node" "$@" ;;
    "")   mu_auth && mu_ssh_login "$target" ;;
    *)    mu_auth && ${MU_SSH:-ssh} -q "$target" "bash -lc \"$*\"" 2> >(grep -vE "${MU_SSH_STDERR_FILTER:-dbus-update-activation-environment|^Cannot continue}" >&2) ;;
  esac
}
`

// Generate returns the shell code to eval at startup: the config as exports (so
// legacy shell consumers — status.sh, mu_kitty_bootstrap — work with config.env
// gone), then the per-node dispatchers. The current system ($MU_NODE, else
// $BC_HOST) is skipped — no self ssh/cp dispatcher.
func Generate() string {
	targets := config.NodeTargets()
	self := selfNode()

	var nodes []string
	for _, n := range config.NodeNames() {
		if n != self {
			nodes = append(nodes, n)
		}
	}

	var b strings.Builder
	b.WriteString("# mayhl_utils shell integration — generated by `mu shell-init` (do not edit)\n")
	b.WriteString(configExports())
	b.WriteString(helper)
	// Clear any stale same-named aliases (e.g. a leftover bare-node ssh alias from
	// the old connect.sh codegen), then define the dispatchers inside a NESTED
	// eval. zsh parses a whole eval block up-front and refuses a function def over
	// a live alias — the nested eval defers parsing the defs until after the
	// unalias has executed. (No dispatcher body contains a single quote.)
	if len(nodes) > 0 {
		fmt.Fprintf(&b, "unalias %s 2>/dev/null || :\n", strings.Join(nodes, " "))
		b.WriteString("eval '\n")
		for _, n := range nodes {
			fmt.Fprintf(&b, "%s() { _mu_node %s \"%s\" \"$@\"; }\n", n, n, targets[n])
		}
		b.WriteString("'\n")
	}
	return b.String()
}

// configExports mirrors config.toml back into the MU_* environment for shell code
// that still reads it (the Go engine reads config.toml directly; this is the
// bridge that lets config.env be retired). MU_SSH stays a platform seam.
func configExports() string {
	var b strings.Builder
	if u := config.HPCUser(); u != "" {
		fmt.Fprintf(&b, "export MU_HPC_UNAME=%q\n", u)
	}
	defs := config.ClusterDefs()
	names := make([]string, 0, len(defs))
	for _, c := range defs {
		names = append(names, c.Name)
		cu := strings.ToUpper(c.Name)
		fmt.Fprintf(&b, "export MU_CLUSTER_%s_DOMAIN=%q\n", cu, c.Domain)
		fmt.Fprintf(&b, "export MU_CLUSTER_%s_NODES=%q\n", cu, strings.Join(c.Nodes, " "))
	}
	fmt.Fprintf(&b, "export MU_CLUSTERS=%q\n", strings.Join(names, " "))
	fmt.Fprintf(&b, "export MU_HPC_RSYNC_OPTS=%q\n", config.RsyncOpts())
	fmt.Fprintf(&b, "export MU_SSH_TRANSFER_OPTS=%q\n", config.SSHTransferOpts())
	fmt.Fprintf(&b, "export MU_SSHFS_ROOT=%q\n", config.SSHFSRoot())
	// ossh binary path (machine-specific) → the platform seam reads it to set
	// MU_SSH. Only emitted when configured, so an unset value falls back to
	// command -v ossh || ssh.
	if p := config.OSSHPath(); p != "" {
		fmt.Fprintf(&b, "export MU_OSSH=%q\n", p)
	}
	return b.String()
}

// selfNode is the node this shell is running on, if any (compute/login nodes set
// $BC_HOST reliably; $MU_NODE is an explicit override).
func selfNode() string {
	if n := os.Getenv("MU_NODE"); n != "" {
		return n
	}
	return os.Getenv("BC_HOST")
}
